#
# Ubuntu Dockerfile
#
# https://github.com/dockerfile/ubuntu
#

# Pull base image.
FROM ubuntu:16.04

RUN apt-get update && apt-get install -y sudo
RUN sudo apt-get install -y libfontconfig libfontconfig-dev libfreetype6-dev libjpeg-dev libssl1.0.0 libssl-dev libxslt-dev libhyphen-dev
# Install.
ADD ./bin /bin

# Define default command.
CMD ["/bin/phantomjs", "-v"]